# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d4c000028ef70664fdd1c744ab1089227d4f3de904d0301f70c7b7e266d1412a24709f4e1cb52eff3e4add331e470a491a0dd97940fcf9468104f662b5cd9f7

test:
  secret_key_base: c04d65b2d7654291a9910dc5c8ed04a427fcfb3b7a069e28d01105fea742a884474f541997ef30e3a48323e719d1d3b22cc430931eaff2ea4ff553c8c0886275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
